egg_DIR_SOURCES := . one_dir other_dir one_dir/nested_dir
#egg_SOURCES := main.cpp

egg_FLAGS += -Wall
egg_RELEASE_FLAGS := -O3
egg_DEBUG_FLAGS += -g

egg_CFLAGS += -std=c99
egg_CXXFLAGS += -std=c++11


include ../../eggmakelib/engine.mk
