* Ongoing Tasks

- multitarget.mk should work by including and not by calling make (go on a new feature branch)

** Create proper examples
   - every feature should have a small working stub project as an example
*** vpath
    show usage of vpath for adding directories.
*** libraries
    when support for libraries is added, library compilation
*** example for importing external, not system libs.
    with custom EXTERNAL_LIBS_DIR

** goalflags.mk
- should remove the staticdebugantani crazyness, read MAKE_CMD_GOALS and do that on the commmand line
do something like current multitarget.mk to read the goals, and do the proper flag override. this could be done in a goalflags.mk file

- check standard targets to provide:
   http://www.gnu.org/software/make/manual/html_node/Standard-Targets.html
- http://stackoverflow.com/questions/4035013/using-gnu-make-to-build-both-debug-and-release-targets-at-the-same-time

** Add support for custom compilation goals, eg for additional cross compilation builds
- a mechanism for custom goals and a mechanism for switching on several gol "types" at the same time should work together.
- the above mechanism should be meta-programmable - the goal <mygoal> is added to a list of goals (egg_GOALS), and the variable <mygoal_FLAGS> is added to egglib_FINAL_FLAGS
- or, whoever is adding the goal could add proper goal/variable handling..
*** old considerations
   - depending on how it's done, should this feature replace the all/debug/..../statictracedebug system (which is ugly anyway)?
   - users should be able to add custom targets of their choosing, which enable different build options. At the end of the makefile they write FINAL_FLAGS and FINAL_LDFLAGS according to the targets.
   - Maybe using metaprogramming in multitarget.mk:
     http://make.mad-scientist.net/secondary-expansion/
   - and/or the foreach function, iterated over a list of possible targets - this would eliminate the copy-pasted code in multitarget.mk

idea: there should be a stdtarget.mk makefile that implements the all/debug/.../statictracedebug system (and should add a release target for additional flags that go in release only?). users could import it or not, and they should have facilities for adding custom target names to the system, and make them work within all other features as they were native.



** Support adding files by directories
   all C/C++ files in the directory will be added as sources, c files as C sources and C++ files as C++ sources. If no sources and no directory are given, default to current dir.

- with sane defaults and support for adding all files in a directory, and SOURCES defaulting to all C/C++ files in the same dir as the makefile, the smallest makefile should build target from SOURCES

**  automatically disable builtin rules, but offer an option for using them
.SUFFIXES:

ifeq ($(filter -r,$(MAKEFLAGS)),)
MAKEFLAGS += -r
endif

** debugging features
- should add variables for debugging the makefile itself and/or making it verbose - if set, warning directives are printed out with target names, object names etc etc

** Avoid copy/paste for multiple C++ extensions
foreach should be the answer, but it is currently not working and commented out in engine.mk.
http://stackoverflow.com/questions/9691508/how-can-i-use-macros-to-generate-multiple-makefile-targets-rules-inside-foreach

** more flexible handling of automatic dependencies generation
   - should add variable to suppress generation of dependencies
   - should add customizable command for dependecies generation

** Create an envsys.mk library for env/system checks
*** write simple functions for if checking
    - check if variable equal a string
    - check if variable equals one in a list of strings
*** Set standard variables for conditional building
    - hostname
    - os family/type/version/kernel etc etc
    - username
*** Macosx
    uname -s
    uname -m / -p / -r
    sw_vers | grep ProductVersion | cut -f 2
*** Windows
    [[http://stackoverflow.com/questions/714100/os-detecting-makefile][detect win vs different linux/mac/unixes]]
    [[https://blogs.msdn.microsoft.com/david.wang/2006/03/27/howto-detect-process-bitness/][detecting architecture on windows]]
    [[http://www.bezem.de/make/CreatingAMakeTemplate.pdf][A pdf that may have suggestion for using CMD.EXE and CL.EXE in a vanilla windows environment]]
*** Linux/Unix
    [[http://stackoverflow.com/questions/3466166/how-to-check-if-running-in-cygwin-mac-or-linux/27776822#27776822][uname table for linux/unix]]
    [[https://www.freedesktop.org/software/systemd/man/os-release.html][documentation on linux /etc/os-release]]
    [[http://linuxmafia.com/faq/Admin/release-files.html][table for other unixes release files]]

*** username recognition as a library
** Add support for creating different directories for different compilation targets instead of cleaning everything.
   - For example, build.release and build.debug (or build.program.debug etctc)
   - Option for choosing between: "only the executable of the last build is left in the root directory (build dirs act as object caches)" vs "the executable is in the build dir". Another possibility: a certain target activates the option "copy executable to root", all other executables stay in the build directory.
   - Optionally, should certain targets be compiled together when doing make all? For example release and debug? Done this way, release should be added as an explicit target type and the only default target for "all".



* Future Tasks
** Support for library compilation
   - What additional features are needed?
   - dynamic and static libraries?
   
** install.sh script
   which exports the library files to a given location.
   - -g,--global (default dir becomes /opt/local/share/, requires sudo)
   - -d,--dir </custom/install/path/> , will append eggmakelib to it, (default dir=~/)
   - -m if installing with -l, remember the directory in a database (./eggmake.local.track). If removing with -r, remove from db.
   - -a perform action on everything on the db
   - -i,--install
   - -c check if version in dir and version in repo differs, and which one is newer.
   - -r remove

** Consider support for multiple executables that share a single build directory structure
   - This would be useful for compiling executables that depend over almost the same set of object files and are often recompiled together. Object files would be copmiled once.
   - Problem: if one executable is recompiled with a different compile option, the other build becomes broken, with the executable and part of the object files still being compiled with the old option. Make now sees an inconsistent state.
   - Solution: executables sharing a build directory with others should always be recompiled together...
   - Maybe it's impossible to support multiple executables in the same makefile - maybe it is, if all multiple targets depend on all object files. This would make sure that every object file is recompiled if the options change.
   - if it's done that way, maybe an option could be added for sharing the build directory for all builds, when compiling releases for installation (no develop mode).

** Consider support for global compilation
- That is, checking subdirectories and compiling every target that is found inside them. A single make in the project root directory should then recompile everything in the project.

- How does this interact with the option for sharing executables? Really, two use cases: development phase, everything is private. Release, everything is shared.

- This could work at directory level, by using a build dir relative to the directory of the launched makefile. In this way, the root dir can be configured for an object-sharing, global build, and subdirs can make development monad-style builds. Problem: does the build dir have a flat structure? With all object files and executables in the same level? Maybe yes!

- test this by compiling all examples all at once in the example directory.

** General aims for makefile calling makefiles:
- include, not recurse
- any single executable should be able to be recompiled by going in the right directory and typing make executable <optional modifiers>
- make inside a directory should recompile every executable in the working directory and subdirectories, and or clean/test everything.

** Facilities for install and dist targets?
   What are the proper actions and defaults here?

** colored outputs for supported terminals
   ideas: put dep compilation in grey, and make real compilation stand out.

** Support an eggmake.conf.mk file
   - Every makefile automatically search for a standard conf file in standard places (same dir, previous dirs until the project root dir, homedir, systemdir etc)
   - The conf file personalizes the default variables that control eggmake.

** Warning: the result of building inside a tree should be level-indipendent.
   - if a sublevel makefile is included by a top level one, variables are inherited.
   - if that same makefile is called in the subdir, results could be different, because variables previously included are missing
   - this would be solved by the conf.mk approach, but we're depending on discipline by the user... which never works
   - the whole "submake" problem must be approached again...

** Facilities for testing (unit testing etc)?
** Incorporate gmsl
   and use its features to help with conditional compiling
   http://gmsl.sourceforge.net/

** Check for compiler versions/features
http://stackoverflow.com/questions/5188267/checking-the-gcc-version-in-a-makefile

** check for system libraries and/or installed programs, and their versions?
